<a href="https://colab.research.google.com/github/INFINITY-RUBER/Curso_de_Tensorflow-2.0_Guia_completa_para_el_Nuevo_Tensorflow/blob/master/Colab_2_Introducci%C3%B3n_a_TensorFlow_2_0_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## TensorFlow 1.X

### Instalar TensorFlow 1.X



In [ ]:
!pip install tensorflow-gpu==1.13.1

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.2.0'

### Constantes

#### Definir una constante

In [4]:
# Definir una constante en TensorFlow
tensor = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [ ]:
# Si la session no ha sido inicializada, no se pueden acceder a los valores de la constante
tensor.eval()

#### Consultar los valores de la constante

In [ ]:
session = tf.Session()

In [9]:
session.run(tf.global_variables_initializer())

In [10]:
tensor_value = session.run(tensor)

In [11]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

### Variables

#### Definir una variable

In [7]:
# Definir una variable de TensorFlow 
variable = tf.Variable([[30, 20], [10, 45]])

In [8]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

In [ ]:
# Si la session no ha sido inicializada, no se podrán acceder a los valores de la variable
variable.eval()

#### Consultar los valores de una variable

In [15]:
# Inicializar una session
session = tf.Session()

In [16]:
# Inicializar TODAS las variables de la session
session.run(tf.global_variables_initializer())

In [17]:
# Ejecutar el método eval en el entorno con la sesión iniciada para recuperar los valores del mismo
variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

## TensorFlow 2.0

### Instalar TensorFlow 2.0

In [ ]:
#!pip install tensorflow-gpu==2.0.0-alpha0


In [9]:
import tensorflow as tf
import numpy as np

In [10]:
tf.__version__

'2.2.0'

### Constantes

#### Definir una constante

In [11]:
# Definir una constante en TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [12]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [13]:
# Obtener el tamaño de un tensor
tensor_20.shape

TensorShape([2, 2])

#### Consultar los valores de una constante

In [ ]:
# Obtener los valores directamente desde una constante de TensorFlow con numpy, sin necesidad de una session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [14]:
# Podemos convertir un array de numpy a un tensor de TensorFlow directamente
numpy_tensor = np.array([[23,  4], [32, 51]])
numpy_tensor

array([[23,  4],
       [32, 51]])

De  Array a Tensor

In [15]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [16]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Variables

#### Definir una variable

In [17]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Consultar los valores de una variable

In [18]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Cambiar un valor especifico de una variable

In [20]:
tf2_variable[0, 2].assign(100) # asignar fila y columna

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [ ]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

## Operaciones con tensores

In [21]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Sumar un escalar a un tensor

In [22]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplicar un escalar por un tensor

In [23]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

## Utilizar funciones de Numpy sobre tensores de TensorFlow

### Obtener los cuadrados de todos los números de un tensor de TensorFlow

In [ ]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

### Obtener la raíz cuadrada de todos los números de un tensor de TensorFlow

In [24]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

### Producto escalar entre dos tensores

In [27]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [25]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [26]:
 np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)

### Producto escalar 

In [36]:
#Producto escalar 
# (filas 1º vector X Colunmas del segundo vector o matriz)
print(1*23 + 2*32)
print(1*4 + 2*51)
print(3*23 + 4*32)
print(3*4 + 4*51)


87
106
197
216


### Strings en TensorFlow 2.0

In [37]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'TensorFlow'>

#### Operaciones simples con strings

In [38]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [39]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

#### Almacenar arrays de strings

In [ ]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [ ]:
# Iterar sobre un array de strings en TF
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
